spring.application.name = ERP

# Database Configuration
spring.datasource.url = jdbc:mysql://localhost:3306/ERP
spring.datasource.username = root
spring.datasource.password =
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto = update
spring.jpa.generate-ddl = true
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# JWT Secret Key (must be 32+ characters)
jwt.secret-key = superlongrandomsecretkeyforjwtgeneration1234
jwt.expiration = 86400000
jwt.refresh-expiration = 604800000

# email settings
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = mu.gloria405@gmail.com
spring.mail.password = rejr apim lpkb guts
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

# Swagger UI
springdoc.api-docs.path = /api-docs
springdoc.swagger-ui.path = /swagger-ui/index.html

# Server Port
server.port = 8000